# motion def:
motion_file: constant_velocity.csv
# IMU params:
imu: 1
# sample frequency of simulated GNSS/IMU data:
sample_frequency:
    imu: 100.0
    gps: 10.0
# topic name:
topic_name: /sim/sensor/imu
gt_topic_name: /pose/ground_truth
# output rosbag path:
output_path: /workspace/data/gnss_ins_sim/my_sim
# output name:
output_name: constant_velocity.bag